# Generated by Django 5.2.12 on 2026-05-05 22:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.00'), help_text='Commission percentage deducted from revenue (e.g. 11.00 = 11%)', max_digits=5),
        ),
    ]
