# Generated by Django 5.2.12 on 2026-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Label for this video e.g. "Awards Night 2024"', max_length=100)),
                ('video', models.FileField(help_text='Upload MP4 video file', upload_to='hero_videos/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — lower numbers show first')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this video from the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Vote for Your Favourite Personality', help_text='Main heading on the homepage hero', max_length=200)),
                ('hero_subtitle', models.TextField(default='Real-time results. Instant MoMo payments. Transparent voting for schools, brands & communities across Ghana.', help_text='Subtext shown below the hero heading')),
                ('hero_badge', models.CharField(default='CrownVote', help_text='Small badge text above the hero heading', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
