# Generated by Django 5.2.12 on 2026-05-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_herovideo_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='herovideo',
            name='hero_heading',
            field=models.CharField(blank=True, help_text='Heading shown on hero when this video plays. Leave blank to use site default.', max_length=200),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='hero_subtext',
            field=models.TextField(blank=True, help_text='Subtext shown on hero when this video plays. Leave blank to use site default.'),
        ),
    ]
