# Generated by Django 5.2.12 on 2026-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_herovideo_hero_heading_herovideo_hero_subtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='hero_heading',
            field=models.CharField(blank=True, help_text='Main heading shown on homepage hero when this video plays e.g. "Vote for Your Favourite Star"', max_length=200),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='hero_subtext',
            field=models.TextField(blank=True, help_text='Supporting text shown below the heading when this video plays.'),
        ),
    ]
