# Generated by Django 5.2.12 on 2026-05-10 00:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_herovideo_hero_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='hero_heading',
            field=models.CharField(blank=True, help_text='Main heading shown on homepage hero when this video plays', max_length=200),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='video',
            field=cloudinary.models.CloudinaryField(help_text='Upload MP4 video file', max_length=255, verbose_name='video'),
        ),
    ]
