# Generated by Django 5.2.12 on 2026-05-10 09:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_herovideo_hero_heading_alter_herovideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
