# Generated by Django 5.2.12 on 2026-08-22 14:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_per_vote',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Price per vote in GHS, set per organizer agreement', max_digits=6),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_badge',
            field=models.CharField(default='NobleVote', help_text='Small badge text above the hero heading', max_length=100),
        ),
    ]
