# Generated by Django 5.2.12 on 2026-08-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_price_per_vote_alter_sitesettings_hero_badge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Change anytime to reorder events.'),
        ),
    ]
