# Generated by Django 5.2.13 on 2026-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
