# Generated by Django 5.2.13 on 2026-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0002_nominee_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='short_code',
            field=models.CharField(blank=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
