# Generated by Django 5.2.12 on 2026-05-10 09:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0003_alter_nominee_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
